### ISSUE TITLE
Tag page does not handle plural and singular post count correctly.

### ISSUE THREAD

**Issue by issmirnov** [mihneadb/no-nonsense#13]
Right now, the tag page always uses the word `posts`, regardless if the post count is 1. I propose a quick fix to enable plurality support:
file: /tag.hbs
find: `pagination.total posts`
replace with: `{{plural pagination.total empty='No posts' singular='% post' plural='% posts'}}`

**Comment by mihneadb** [comment]
Fixed in #14.
