### ISSUE TITLE
Possible change to tag page - include description?

### ISSUE THREAD

**Issue by issmirnov** [mihneadb/no-nonsense#15]
Hey,

I was checking out the Ghost docs and noticed that we now have a tag manager, and a way to add descriptions, images, and SEO data to tags. Do you think it's worth incorporating the tag description on the /tag/tag-name page? 

Default to post count, but if there is a description that is shown instead:
- [tag with descritption](http://cloud.ivansmirnov.name/image/073C253T3G3F)
- [tag with empty description](http://cloud.ivansmirnov.name/image/1V2138192534)

What do you think?

**Comment by mihneadb** [comment]
Yep, I like it. Feel free to make a PR! Good catch! :)

**Comment by issmirnov** [comment]
Created!

**Comment by mihneadb** [comment]
Closed in #17
