### ISSUE TITLE
Implement custom error page

### ISSUE THREAD

**Issue by issmirnov** [mihneadb/no-nonsense#21]
Ghost allows theme developers to provide a custom error page to be served in place of the default one. I think it would be awesome to have a clean page that can apologize for the error and guide the visitor back to the blog. 

Some thoughts on layout and style:
-  Keep it similar to the existing theme template
- Have the error code somewhere on the page, so people understand what's happening.
- Main focus should be a nice flow back to the main content - either a list of recent posts, or an inviting button to navigate back home
- If possible, figure out whether this is a 404, and if so, add a cute message (there's many examples online)
- All of this is done in a minimalistic style, consistent with the theme.

Thoughts?

P.S. Some resources: https://github.com/TryGhost/Ghost/blob/master/core/server/views/user-error.hbs, http://www.ghostforbeginners.com/custom-error-page/

**Comment by mihneadb** [comment]
Sounds great! Can we have any other error pages than 404? Are you thinking 500?

+1 for the cute message. I *think* that a small list of posts might fit better with the style than a button. It's more of a text-first approach overall.

**Comment by issmirnov** [comment]
Yep, all error codes are ours to catch. There are some helpers, `{{code}}` and `{{message}}` that provide the details. I don't know of a good way to test for equality in hbs files though, so not sure if a generic error message is all that's possible, or if it can be tailored.

Regarding the post list, what's the helper for listing them? Are you thinking the last N posts, or something like that?

**Comment by mihneadb** [comment]
Right, we can't do any comparisons in hbs. Let's go with something else: a cute message for `an error has occurred but here's a list of the latest posts`.

Post list: https://github.com/mihneadb/no-nonsense/blob/master/partials/loop.hbs

What do you think? If the `posts` helper that's used in `loop.hbs` is not available, we could just leave a link (not button) to `@blog.url` and that's it.

**Comment by issmirnov** [comment]
I checked, seems the post helper isn't available. Threw together some code over lunch:
https://github.com/issmirnov/no-nonsense/blob/error-page/error.hbs
![image](https://cloud.githubusercontent.com/assets/5771615/6744027/e591de04-ce5f-11e4-8937-d22de63b9548.png)

I'll be on a trip till April, so if you want to hack away on it as well by all means!

**Comment by mihneadb** [comment]
Haha, cool. I'll try to find something shorter in the meantime.

Enjoy your trip!

**Comment by issmirnov** [comment]
Hey, I'm back. Did you have time to take a look?

**Comment by mihneadb** [comment]
Hey there, sorry for the delay.

I had an idea, what if we also used a photo? Here are some examples:

Message about something like "you took a wrong turn" or "dead end" or something like that.

![brick-wall](https://cloud.githubusercontent.com/assets/643127/7039701/37c7790e-ddce-11e4-85b7-94680d7ba116.JPG)

Message about "got lost", or "nothing is here", something like that.
![d9xlw7uxtbqqw5slf8cj_reef insp-72](https://cloud.githubusercontent.com/assets/643127/7039702/37c8d826-ddce-11e4-85cf-a51d8856e14b.jpg)

I think I like the first one better. The photos are "do whatever you want with them" from https://unsplash.com/, so that's cool.


What do you think?

**Comment by issmirnov** [comment]
I really like the first one as well. Good call!

**Comment by mihneadb** [comment]
:D

On Wed, Apr 8, 2015 at 11:53 PM, Ivan Smirnov <notifications@github.com>
wrote:

> I really like the first one as well. Good call!
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/mihneadb/no-nonsense/issues/21#issuecomment-91034161>.
>



-- 
Mihnea Dobrescu-Balaur

**Comment by mihneadb** [comment]
I'm not sure, I think a central box would fit the overall style better. Kind of like the post photo looks now. BTW, we'd have to reduce the photo's resolution a bit.

**Comment by issmirnov** [comment]
Makes sense. Do you want me to look into it, or planning on throwing up some code yourself?

**Comment by mihneadb** [comment]
Went ahead and implemented it! :) Thanks for the suggestion and the help!
